### ISSUE TITLE
Missing account Id in receipt error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#1008]
### Description

Receipt errors sometimes report a 0.0.0 for the account id part of the transaction id, e.g.

```
 status: false,
  error: 'receipt for transaction 0.0.0@1647420308.170285866 contained error status TOKEN_NOT_ASSOCIATED_TO_ACCOUNT'
  ```

### Steps to reproduce

not found a consistent way of reproducing this

### Hedera network

mainnet, testnet, previewnet

### Version

v2.10.1

**Comment by danielakhterov** [comment]
I don't know why it took me this long to realize, but this seems to be correct. As in, the transaction ID that is printed in the `ReceiptStatusError` and `PrecheckStatusError` for queries is the payment transaction ID. For `AccountBalanceQuery` and `TransatcionReceiptQuery` the payment transaction ID will be generated from an account ID of `0.0.0` because they're both free queries. For `TransactionReceiptQuery` I can see how this seems backwards, and perhaps instead we should be using the transaction ID set on the `TransactionReceiptQuery` instead of the payment transaction ID, but what about `AccountBalanceQuery`? I'm not really sure what we should do there.

**Comment by danielakhterov** [comment]
I resolved the issue for `TransactionReceiptQuery` https://github.com/hashgraph/hedera-sdk-js/commit/bfa87bf1b5f771cafd3fdf13f5c34a27841136e7 I'm not sure what is the best approach for `AccountBalanceQuery`, so I'm closing this for now (since the issue wasn't asking about `AccountBalanceQuery`). It may be a good idea to create a separate issue for that though.
