### ISSUE TITLE
Difference in set Contract constructor parameters and Contract set function parameters

### ISSUE THREAD

**Issue by PatMat-Ariane** [hashgraph/hedera-sdk-js#1041]
### Problem

I found a little difference when setting parameters for `ContractCreateTransaction.setConstructorParameters` and `ContractExecuteTransaction.setFunction`, in the first method is checking if the constructor parameter type` == ContractFunctionParameters` is not present in the second method.

### Solution

Add check type for `ContractExecuteTransaction.setFunction` function parameters like in `ContractCreateTransacion.setConstructorParameters`

**Comment by danielakhterov** [comment]
I don't think this is a bug because although the methods look similar, they're actually slightly different. In `ContractCreateTransaction` we have one method to either `Uint8Array` or `ContractFunctionParameters`, but in `ContractExectueTransaction` we have two methods `setFunction` and `setFunctionParameters`. The reason we made this separation in `ContractExecuteTransaction` is because for the former the `name` of the function the user is calling is required, while in the latter the name should already be encoded in the byte array. So, `ContractExecuteTransaction.setFunction()` doesn't support passing in `Uint8Array` and hence doesn't need to check the type is `ContractFunctionParameters`
