### ISSUE TITLE
Transaction needs to be created using a third party time source

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1103]
### Problem

By far the most user issues we field are from the INVALID_TRANSACTION_START error, and every single time it is because the users computer clock is wrong.

As a wallet, we do not always create the transactions, sometimes they come from external dapps. Please consider using some sort of third party clock rather than the local one.

### Solution

Use third party time source

**Comment by danielakhterov** [comment]
I'm not completely following what you mean with
> Use third party time source

Do you mean we should query a NIST https://tf.nist.gov/tf-cgi/servers.cgi

Nonetheless, I really don't think this is something the SDK should be doing, and I have several questions and concerns:
1) Why isn't the user's clock right?
2) Why should the SDK pave over the fact the user's clock is wrong?
3) If we were to query a NIST Time Services then it'd require `Transaction.freezeWith()` to be async and hence a breaking change. This would be the case even if we were to make querying a third party time source optional.
4) This would make freezing transactions considerably slower since it'd require a query each time.
5) Do you have any examples of other libraries doing such a thing?

**Comment by teacoat** [comment]
Maybe the sdk could query the time source once, and check the difference with the current client time and take the difference into account or something

**Comment by danielakhterov** [comment]
@teacoat We've been getting reports that this feature is causing CORS issues in browsers, so we're going to disable this feature in browsers. I'm not sure if the dapps you were referencing were browser apps, because if they were then the issue might resurface.

**Comment by teacoat** [comment]
@danielakhterov yes they were browser-based transactions, as those are the ones affected by client-side clocks

**Comment by danielakhterov** [comment]
So that'll definitely be an issue going forward. However, the work around is that you can take the sync code we have now, and apply it in your application? So the feature is still _sort of_ supported, but at the same time won't cause others to hit CORS issues.

**Comment by teacoat** [comment]
Fantastic! You're killin it, thanks a lot man

**Comment by teacoat** [comment]
uh oh @danielakhterov, looks like one more minor error in the browser:
![image](https://user-images.githubusercontent.com/3913019/176095315-64ae13f0-b5c5-4aa7-aaf9-99696f5d9b42.png)

![image](https://user-images.githubusercontent.com/3913019/176095352-8de6a52e-cfb2-4804-8d6a-4d33e1febbfe.png)

Seems to be causing errors -

![image](https://user-images.githubusercontent.com/3913019/176095394-6cc6857a-88d0-4e69-9e57-9a0aa2019725.png)

**Comment by teacoat** [comment]
@danielakhterov I think its the other way around, whatever is requesting from [https://grpc-web.myhbarwallet.com:443](https://grpc-web.myhbarwallet.com/) isn't including a content type in the request?

**Comment by danielakhterov** [comment]
Ah, I think you're right. However, shouldn't the use of `HEAD` completely remove the need to set content type?

**Comment by danielakhterov** [comment]
@teacoat Released https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.16.4-beta.1 as a beta to see if this solves the issue. If it does I'll do an official release.
