### ISSUE TITLE
AccountAllowanceApproveTransaction response EMPTY_ALLOWANCES

### ISSUE THREAD

**Issue by cmdhema** [hashgraph/hedera-sdk-js#1104]
### Description

Always precheck return 'EMPTY_ALLOWANCES' when I try AccountAllowanceApproveTransaction.

![image](https://user-images.githubusercontent.com/8086332/165597434-b1f08cdb-5843-4f4a-8b8c-b98f69e80127.png)

### Steps to reproduce

Try to run

![image](https://user-images.githubusercontent.com/8086332/165597168-7b2c3a50-656f-4319-b054-d0ff28b57352.png)

### Hedera network

testnet

### Version

v2.13.1

### Operating system

macOS

**Comment by ed-marquez** [comment]
The shipping example also fails: https://github.com/hashgraph/hedera-sdk-js/blob/main/examples/account-allowance.js

**Comment by danielakhterov** [comment]
Yea, this seems to be because the Java SDK updated the example and the JS didn't update along with it.

**Comment by danielakhterov** [comment]
This took a lot longer than it should have, but the issue is that the protobufs have been updated since the last release which contained breaking changes. Fixed here: ddc565a9b21cbe67bbd7e5f5d65f1618e48450cc and published a new `@hashgraph/proto` version. This shouldn't really require a SDK release from what I can tell, so if you add
```json
  "overrides": {
    "@hashgraph/proto": "2.4.1"
  }
```
to your `package.json` it _should_ work

**Comment by cmdhema** [comment]
@danielakhterov I try installed proto 2.4.1 but the result is same. I will wait sdk version up.

**Comment by danielakhterov** [comment]
Hmm, yea tested that as well with the example and it doesn't seem to work :( I think that's fine though since I will be releasing some SDK version tomorrow so you won't have to wait long.
