### ISSUE TITLE
Unable to create token - Expiration and Renewal Period now?

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1179]
### Description

Updated from 2.14 to 2.16 and create token transaction seems to be failing with invalid expiration/renewal error.

![image](https://user-images.githubusercontent.com/3913019/176584790-94bcf740-9612-4257-8aca-2a775cbb36cd.png)

### Steps to reproduce

Try running a similar transaction to this:

let trans = new TokenCreateTransaction()
                .setTokenName("Test Token")
                .setTokenSymbol("TEST")
                .setTokenType(TokenType.FungibleCommon)
                .setDecimals(2)
                .setSupplyType(TokenSupplyType.Finite)
                .setInitialSupply(100000)
                .setTreasuryAccountId(userSigningAcc)
                .setAdminKey(pubKey)
                .setSupplyKey(pubKey)
                .setWipeKey(pubKey)
                .setExpirationTime(new Date().getTime() + 1000)
                .setAutoRenewPeriod(100)
                .setAutoRenewAccountId(userSigningAcc)
                .setMaxSupply(1000000);

Should fail with invalid expiration or renewal, didnt need to set these before and setting them doesn't seem to work

### Hedera network

testnet

### Version

2.16

**Comment by danielakhterov** [comment]
@teacoat I'm a little confused here. You're saying this _should_ error or _shouldn't_ error? I did a quick test and `TokenCreateTransaction` seems to be working fine when I comment out both `setExpirationTime()` and `setAutoRenewPeriod()`. The reason it errors when either of those are uncommented is simply because those are in fact invalid expiration times/renew periods; 1000 seconds is too small _iirc_.

**Comment by teacoat** [comment]
@danielakhterov Sorry for the word salad lol, it should be successful when leaving out the expiration and renew period, never needed to set those before and it seems to be failing now without those

**Comment by danielakhterov** [comment]
@teacoat I just re-ran https://github.com/hashgraph/hedera-sdk-js/blob/1f4c4d624422a00bb2b5c8a9e1a2eea5f1dd09b7/test/integration/TokenCreateIntegrationTest.js#L11 using a previewnet account and the test is passing. That test doesn't set either `expirationTime` or `autoRenewPeriod`. Are you on a different version of the SDK that perhaps was had a bug?

**Comment by teacoat** [comment]
@danielakhterov i tried with 2.16 as well as 2.17 and I was still getting it, will try again and collect more details

**Comment by danielakhterov** [comment]
@teacoat While I was working on https://github.com/hashgraph/hedera-sdk-js/pull/1207 I got `TokenCreateTransaction` to fail in the example `transfer-tokens.js`. The only time this issue would pop up is if you're using a `Wallet` instead of a `Client`. I did fix this in that PR, but a work around is set the auto renew account ID using `setAutoRenewAccountId(wallet.getAccountId())`. What I think is happening is the auto renew period is ignored if the auto renew account ID is unset, but instead of erring indicating the auto renew period is being ignored because of that, the services simply error with invalid auto renew period / expiration time.
