### ISSUE TITLE
Avoid suggesting internal methods (in VS Code)

### ISSUE THREAD

**Issue by michielmulders** [hashgraph/hedera-sdk-js#1203]
### Problem

When using the JS SDK in VS Code, it often suggests internal methods (first) which is sometimes annoying if you want to quickly scroll through the public ones that are available. Here's an example for the `ToeknAssociateTransactoin`:

<img width="486" alt="Screenshot 2022-07-25 at 22 41 43" src="https://user-images.githubusercontent.com/26482710/180874932-d18c7de8-dd22-4adc-b41b-f92f9552b706.png">

This is the [respective `Transaction.js` file](https://github.com/hashgraph/hedera-sdk-js/blob/1f4c4d624422a00bb2b5c8a9e1a2eea5f1dd09b7/src/transaction/Transaction.js#L1276) which exports the entire class

### Solution

Don't export internal methods.

**Comment by danielakhterov** [comment]
Unfortunately, we cannot fix _all_ these methods because of classes like https://github.com/hashgraph/hedera-sdk-js/blob/main/src/query/CostQuery.js but I went ahead and fixed several of the `_build` methods. The issue really is that TS does not have a way to mark a method as package private which is necessary for us since some classes require access to internal methods from outside the class definitions.

**Comment by michielmulders** [comment]
Thanks for that update!

**Comment by danielakhterov** [comment]
I forgot, but there is another way to suppress the internal methods. Pretty sure I suppressed the memory because how disgusting it is, but it does work. It would require us to use `Symbol()` for any private field/method. Meaning, this issue is actually fix-able currently and we should do it even though it would be very ugly.

**Comment by mehcode** [comment]
Not possible to fix this without a large breaking change.
