### ISSUE TITLE
AccountInfoQuery - Deprecate and remove documentation for the allowances fields in AccountInfo

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1211]
### Description

Mirror node queries show shows the allowance approved by an owner account:
https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.2917624/allowances/crypto

An AccountInfoQuery for the same account via the SDK does not show any allowance information.

### Steps to reproduce

See lines 128-131 in the code sandbox:
https://codesandbox.io/s/hedera-example-contract-allowance-sdk2-onzzik?file=/index.js

Node index.js 

See no info - 
The same happens when placing breakpoints and inspecting the query results objects in more detail (screenshot below)

### Additional context

<img width="228" alt="queryBug" src="https://user-images.githubusercontent.com/72571340/181771311-5031c1a4-24df-4779-9fbd-b7f43530fca3.png">

### Hedera network

testnet

### Version

v2.17

### Operating system

Windows

**Comment by mehcode** [comment]
I'm unsure why the `AccountInfo` type in the SDK contains those fields. The network does not return this information. 

See: https://github.com/hashgraph/hedera-protobufs/blob/main/services/crypto_get_info.proto

---

@danielakhterov @SimiHunjan Can we deprecate/remove these fields?

**Comment by ed-marquez** [comment]
@mehcode - I would suggest leaving this issue open for further input.
The sample output in Documentation also shows those fields for this query: https://docs.hedera.com/guides/docs/sdks/cryptocurrency/get-account-info

It seems to me the issue exists. If the network is not returning the value, then should it? Should we let the services team know? 
I'm surprise by how quickly this issue was closed...

The information is also there for token allowances in the SDK query:
![image](https://user-images.githubusercontent.com/72571340/181811450-59b7ac9a-6e54-4954-b40a-cd8b1fcfeac0.png)

**Comment by mehcode** [comment]
It was closed because this isn't a SDK issue and I'm trying to keep the SDK issues clean. If we want to discuss whether this should happen at the network repo, we can open a discussion here or in the services repo. 

The field is there in the SDK object likely because Hedera _used_ to return it. They no longer do. I don't have any other context there.

My personal guess is its far too expensive for the network to return an array of all allowances and Hedera is going to leave this to the mirror network. We may want to expose more mirror network services in the SDK, but that's a separate discussion as well.

**Comment by mehcode** [comment]
Re-opened to track fixing the documentation and explicitly deprecating these fields.

**Comment by danielakhterov** [comment]
I didn't realize this at the time, but those fields are already deprecated on `main` https://github.com/hashgraph/hedera-sdk-js/blob/df182a16dce4ca3f58432c10edcca2fe9d9126b9/src/account/AccountInfo.js#L214 As for removing those fields that breaks semver meaning it requires further discussion before we proceed.
