### ISSUE TITLE
FileAppend fails with expired transactions on mainnet

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#1213]
### Description

uploading a large file with fileAppend on mainnet results in expired transaction errors. This is presumably because all the transactions are prepared in advance and a large number of chunks results in a file upload taking longer than 2 minutes in total, leaving some transactions to expire.

### Steps to reproduce

Upload 30k file using fileAppend on mainnet (it works on testnet, but not mainnet where consensus latency is a little higher).

### Hedera network

mainnet

### Version

v2.17.0

**Comment by danielakhterov** [comment]
Will need to investigate further, but this _should_ already be handled here: https://github.com/hashgraph/hedera-sdk-js/blob/df182a16dce4ca3f58432c10edcca2fe9d9126b9/src/transaction/Transaction.js#L1383

**Comment by danielakhterov** [comment]
@gregscullard I forgot but we already have a test for this https://github.com/hashgraph/hedera-sdk-js/blob/main/test/unit/AccountInfoMocking.js#L350 You do need to enable `[Client.Transaction]signOnDemand` though as by default that option is off. Although we have another option `[Client|Transaction].regenerateTransactionId` the reason this field is ignored is because it requires `signOnDemand` to also be enabled. It's not that obvious though.
