### ISSUE TITLE
Can not load local provider in project

### ISSUE THREAD

**Issue by harryEth** [hashgraph/hedera-sdk-js#1246]
### Description

```
./src/App.js
Attempted import error: 'LocalProvider' is not exported from '@hashgraph/sdk'.
```

I got this error when I tried to load lLocalProvider. Does anyone know why this happened?

### Steps to reproduce

```
import {
    Wallet,
    LocalProvider,
    PrivateKey,
    AccountCreateTransaction,
    Hbar,
    Mnemonic,
    AccountId
} from "@hashgraph/sdk";

```

just import the local provider to the react

node v14.17.0
react 17.0.2

### Additional context

<img width="652" alt="image" src="https://user-images.githubusercontent.com/33265609/186728293-089e610e-ea1d-472c-baca-62f959765424.png">

### Hedera network

mainnet

### Version

"@hashgraph/sdk": "2.13.0",

### Operating system

macOS

**Comment by danielakhterov** [comment]
The JS SDK for browsers does in fact not re-export `LocalProvider` because it uses environment variables to build the internal `Client`, and browsers do not have environment variables. However, `LocalProvider` is a very thin wrapper around `Client.forName(process.env.HEDERA_NETWORK)` so if you'd like you can copy the implementation and change `process.env.HEDERA_NETWORK` to something you do have access to in browsers.
