### ISSUE TITLE
Message chunking - errors and retries

### ISSUE THREAD

**Issue by anvabr** [hashgraph/hedera-sdk-js#1333]
### Problem

When a message to be sent to a topic is larger than 1024 bytes it gets split into chunks.  I believe Hedera SDK is responsible for this task, however the error conditions behaviour of this process does not seem to be documented anywhere. Main question: what happens if for some reason one of the chunks does not get sent? For example, in a message that got split into 3 chunks what would happen if chunk 1 gets sent successfully, chunk 2 fails... - what happens here?

This is a practical issue for us, please see https://github.com/hashgraph/guardian/issues/1290

### Solution

Add clear documentation on:

- how SDK handles error conditions
- how could client application ensure that in the case of failure either everything or nothing gets sent to Hedera?

**Comment by petreze** [comment]
Good morning @anvabr, I have answered to your issue in [hashgraph/guardian](https://github.com/hashgraph/guardian/issues/1290) repo. In regards to your questions, each chunk of topic message submission is treated as a separate transaction. All transaction errors that may appear from a transaction execution, are applied here. For the second question, it is a little bit tricky. Since each chunk is sent as a separate transaction. Lets say the 1st chunk gets submitted properly, which means that there is a consensus and it is persisted to the state. If we have an error when trying to submit some of the other chunks, we would have to somehow revert the state and remove the submission of the previous chunks, which I am not sure if ti is the right approach

**Comment by anvabr** [comment]
@petreze than you for the response and comments. If I am to paraphrase what you said - the submission of message chunks is independently handled in case of errors, is this correct? Meaning if one chunk fails the system just goes and submits the rest regarldess?

We don't have the code that reliably reproduces this problem since it's intermittent, but I am not sure it is needed. It seems we are in agreement that this may happen, even if it is unlikely. I am wondering what can application code do to handle this error properly.

**Comment by anvabr** [comment]
@petreze Thank you for your response. Your description of the scenario-case is spot on - this is the issue we are facing. However I don't advocate for the 'cancelling of transactions' - I perfectly understand the 'immutable ledger' WORM storage of blockchain is incompatible with this idea. However something needs to be done here, because this needs to be atomic from the point of view of the application code. Perhaps there should be a mechanism of 'conditional consensus' on the multi-part messages in Hedera where they don't consider to be 'submitted' and consensus achieved while there is no consensus for all of their parts? Or some sort of atomic 'flag' which switches on/off previously submitted chunks?

**Comment by anvabr** [comment]
Hi @petreze, just reaching out to see if there's been some progress on your discussions with the team?

**Comment by petreze** [comment]
@anvabr 
Up until now we did not come up with a possible solution that **won't** affect badly the consensus service and the main ideology of the whole distributed ledger technology space... TBD

**Comment by anvabr** [comment]
@petreze Happy New Year! Just wondering if there's been any progress here please?

**Comment by petreze** [comment]
@anvabr Happy New Year to you too!
Yup, we had an in depth conversation about this issue but unfortunately, as previously stated, this is strongly against the whole concept of the space and it will include to revert any successfully submitted chunk prior to an unsuccessful one. We cannot make any changes to the state once a transaction(chunk) has reached consensus and is submitted to the state.

Furthermore, as mentioned in the [issue](https://github.com/hashgraph/guardian/issues/1290#issuecomment-1330132980) inside the guardian repo, `payer_account_id` of the third message differs from the other two messages, so the message is most probably signed and executed by other client and persisted as a separate message and thats why I wanted some code example or snippet to try and reproduce it

**Comment by anvabr** [comment]
@petreze Thank you for your response, although I am not sure how to take it. To paraphrase what you wrote, you are saying that **the only possible way** of dealing with that **that you see** is to 'revert transactions'. Since you deem this is unacceptable, **you are not going to do anything at all** about this issue. Is my understanding correct?
 
I already replied to your comment about the [issue](https://github.com/hashgraph/guardian/issues/1290#issuecomment-1330132980) and the `payer_account_id `previously. The content of that particular issue is irrelevant here, the issue has been seen in the wild, albeit rarely, and more importantly intermittently. Are you implying the situation described is not possible?

**Comment by anvabr** [comment]
@petreze Please consider other options - not reverting transactions, but someway else mitigating the issue. Suggesting that each applications by itself solves this problem does not make any sense - if _each_ application needs to solve this problem it, by definition, means it must be solved down the stack! Please brainstorm other possible solutions.

**Comment by anvabr** [comment]
@SimiHunjan @petreze please could you update us on your current thinking in here.

**Comment by SimiHunjan** [comment]
@anvabr can we schedule some time discuss with the team? I am on the Hedera server on Discord (simihunjan). If you can send me your contact details there or if you are in the Hedera ecosystem Slack channel I can message you there if you provide your username. Thanks!

**Comment by anvabr** [comment]
Hello @petreze, thank you for creating the sample code on how to retrieve chunk statuses - it is useful. However ability to do so does not fully resolve our issue. As discussed, it's not only on the 'submitting' side that we have a problem but on the 'receiving' one as well. Topic messages are used as a communication medium and the receiving end (the 'reader') must also have a way to identify that a chunk failed to be sent/delivered and thus the message it is reading is a 'failed' one and should be ignored. Please could you re-open this ticket?

**Comment by anvabr** [comment]
@ochikov We've had a call with your team about a month ago where we have discussed the 'reader' issue at length. To summarise, this is a messaging protocol - posting a message should be guaranteed and atomic so the readers should either do receive it (read it in full) or not at all. At present the sender may become aware that there was a problem with one of the chunks (may be using the examples you created), but it does not change the fact that the incomplete message is still recorded with AFAIK no indication for readers that it's a failed one, that it is missing a piece. No indication which piece is missing as well. This is like a 'UDP' protocol, which allows for packet drop. However 'UDP' is absolutely not appropriate in this context, it is expected and required to be atomic and guaranteed which is 'TCP'.

**Comment by petreze** [comment]
@anvabr 
As you mentioned, we had a higher level discussion with @SimiHunjan and @gregscullard  and we decided that, there is nothing more to do here.

To your question - `the reader must also have a way to identify that a chunk failed to be sent/delivered and thus the message it is reading is a 'failed' one and should be ignored`: you could inform that it is a failed one and exactly which chunk had failed following the example [here](https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/topic-message-submit-get-all-chunks-status.js). Thus, the following chunk could be resubmitted or the entire message itself.

**Comment by petreze** [comment]
@anvabr, sorry for misleading you, I had a look again into the `TopicMessageSubmitTx` and it seems that you don't have the possibility to submit a single chunk itself. I will have further look if there is a chance to make it easier for your specific case and will update you if I find something. Until then, I would suggest the other option - to resubmit the entire message if you encounter a failed message chunk. As you mentioned, this does not appear regularly, so this would be a nice solution. Also, because it cannot be reproduced on demand, it is pretty hard to test and implement a solution.

**Comment by anvabr** [comment]
@petreze thank you for clarifying, the capability to resend the chunk would've been very handy. Please would you be willing to work on adding this capability to the SDK? This would be a workaround we could use!

Just to be clear, resubmitting of the entire message **does not work** for our use-case, it is not an acceptable solution in any sense of the word (not as a 'good enough', not as a 'workaround', not as an etc). We seem to be going in circles on this, as discussed before the reader would still end-up reading of the broken message with missing chunks and get confused.

We fully appreciate the complexity of the development task here, that's why we are reaching out to you - the experts in this area, rather than attempting to produce a PR ourselves. The good news is that it seems as a result of the lengthy discussion we have found an acceptable work-around  - resubmitting the failed chunk - which could address the issue for us. It's not great (it would've been best if the SDK handled these problems somehow  transparently), but it'd do for us in the near future.

**Comment by anvabr** [comment]
@petreze Please can you re-open this ticket, let's please consider if the re-submit for a message chunk is feasible.

**Comment by petreze** [comment]
@anvabr 
By `I would suggest the other option - to resubmit the entire message if you encounter a failed message chunk` I meant the following thing: I assume that you are making `TopicMessageSubmitTx`, then you can check, following the [example](https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/topic-message-submit-get-all-chunks-status.js), if there is a failed chunk. If there is - resubmit the entire message. This happens **_before_** displaying or sending the message to the reader! This means resubmitting the entire message on failed chunk on _**your**_ side before sending it elsewhere. In that way you ensure on _**your**_ side that the whole message with all the chunks is successful.

In regards to all future possible enhancements e.g: `a possible submission of a single chunk and/or automatic resubmission of a failed chunk` - these approaches should be discussed with the foundation itself, followed by reasonings of the problem, possible solutions or approaches and so on. As I don't know if it should be made possible or if its in the roadmap etc. Things can also escalate into creating an official HIP (Hedera Improvement Proposal). Some [tips](https://hips.hedera.com/) over here..
This is what I'm trying to state since basically the beginning of our discussion here. And also this is why we had the higher level meeting so you can explain a little bit more and present your problem. Then we had a discussion and a **conclusion** was made. Hence, the ticket was closed

**Comment by anvabr** [comment]
> This happens **_before_** displaying or sending the message to the reader! This means resubmitting the entire message on failed chunk on _**your**_ side before sending it elsewhere. In that way you ensure on _**your**_ side that the whole message with all the chunks is successful.

@petreze  This **does not work** for our use-case as I previously stated, please refer to my earlier message for the explanation why that's the case. 

>  these approaches should be discussed with the foundation itself
