### ISSUE TITLE
Error getting nodes from mirror for file 0.0.102 during attempt 5

### ISSUE THREAD

**Issue by ayushkumar731** [hashgraph/hedera-sdk-js#1403]
### Description

I deployed the app on the prod server, getting this error `Error getting nodes from mirror for file 0.0.102 during attempt 5. Waiting 8000 ms before next attempt: No connection established` in Mainnet.

### Steps to reproduce

1. Deployed the web on the AWS server.
2. start the server with the help of PM2.
3. Getting an error after sometime, again and again

### Additional context

<img width="1440" alt="Screenshot 2023-01-21 at 1 41 04 PM" src="https://user-images.githubusercontent.com/65681501/213904514-62170604-e601-4efd-b5dc-f29d03b77053.png">

### Hedera network

mainnet

### Version

v2.18.1

### Operating system

Linux

**Comment by ochikov** [comment]
@ayushkumar731  This is known behavior and you need to update to the latest version. This is an error that the Address Book cannot be updated. In your particular version, the address book is loaded every 10 seconds, thus making the remote server unresponsive due to high demand. You can also try to set `setNetworkUpdatePeriod` to the Client.

**Comment by ayushkumar731** [comment]
> @ayushkumar731 This is known behavior and you need to update to the latest version. This is an error that the Address Book cannot be updated. In your particular version, the address book is loaded every 10 seconds, thus making the remote server unresponsive due to high demand. You can also try to set `setNetworkUpdatePeriod` to the Client.

After the updated library. It's working fine. Thanks!
