### ISSUE TITLE
Invalid Exception during multiple minting

### ISSUE THREAD

**Issue by sehyoung-james** [hashgraph/hedera-sdk-js#1454]
### Description

on mainnet, we have got strange error during minting as below.
- exception: transaction 0.0.1112163@1674796073.250093810 failed precheck with status FAIL_INVALID
but hashscan says that minting tx has been success 
(https://hashscan.io/mainnet/transaction/1674796082.966612026?tid=0.0.1112163-1674796073-250093810)

this exception has been occured during trying to minting 2500 NFTs.
from the client side, minting to 950th is suceess

and after that, we got that error.
but actually minting to 960th is success as shown in hashscan

we have designed the logic so that we can continue minting from the fail position when occurring exception. 
but because of this kind of situation, we can't continue minting
(our db maintains the minted value up to 950, but in reality it is minted up to 960.)

### Steps to reproduce

we have executed below logic on mainnet for minting 2500 NFTs

------------------------------------------------------------------------------------------------
as a reference, our logic looks like as below.
async function asyncTokenMintTransaction(operator, bcTokenId, metadataBufferList) {
    const transaction = new TokenMintTransaction();
    transaction.setTokenId(bcTokenId);
    transaction.setMetadata(metadataBufferList);
    transaction.freezeWith(operator.client);
    const transactionSigned = await  transaction.sign(PrivateKey.fromString(operator.private_key));
    const response = await transactionSigned.execute(operator.client);
    const transactionReceipt = await response.getReceipt(operator.client);
    return transactionReceipt;
}

async function mintingNFT( ... ) {
    while (!(no more nft data to mint)) {
        // prepare metadata(separateSetMetadatas) for this time minting 
        // separateSetMetadatas is holding the metadata for 10 nfts

        // mint, we request to minting 10 nft at one time.
        const receipt = await hedera.asyncTokenMintTransaction(operator, bcTokenId, separateSetMetadatas);

        // do something
    }
    return ;
}

### Hedera network

mainnet

### Version

v2.18.1

### Operating system

Linux

**Comment by petreze** [comment]
Hello @sehyoung-james 
I tried the same setup: minting 2500 NFTs in batches of 10, so in total 250 iterations
The result was that all of them were successfully minted.

Also, just to point out that status `FAIL_INVALID` states a system error and the transaction failed because of invalid request parameters. This basically suggests that something unusual happened on the services side. Might also have something to do with the state of the network at the given time. Given the fact that so many previous iterations were successful, I think that the state of the network was the issue (perhaps it might have something to do with the throttling at that time or something else)
I would suggest to try handle the eventual appearance of this error on your side: maybe by checking if the NFTs were in fact minted if the error occurs

**Comment by sehyoung-james** [comment]
@petreze 
Thank you for your test and review comments.
I agree with your comments about FAIL_INVALID .
However, the problem seems to be that the same minting request was processed as success on one side and registered as success on hashscan, and the other side generated a FAIL_INVALID error.
Because of this phenomenon, it is impossible to handle exceptions for errors in dapp.

I would like to ask if there is any room for improvement in the part where the same minting request gives different results.

**Comment by victorholo** [comment]
I have noticed similar issues, in a node scripts but also in the browser, through HashPack, where you would get an error but the transaction would be successful as could be seen on HashScan. 

This has happened with different types of transactions (Smart Contract transactions mostly I believe) from what I can recall and also I believe has happened the other way around, where you would get a success status back but the transaction would have failed.

Here is an example :
This is the transaction that errored out and please notice the timestamp:
`PrecheckStatusError: transaction 0.0.1041055@1673888915.657072515 failed precheck with status INSUFFICIENT_TX_FEE`
Here is the confirmed transaction, where the `tid` timestamp is before the timestamp in the error and the consensus timestamp is after:
https://hashscan.io/mainnet/transaction/1673888924.859310014?tid=0.0.1041055-1673888912-639808678 

This transaction has been run from a script and there wasn't any batch of transactions this being the only one.

**Comment by petreze** [comment]
It is in fact a strange behaviour, will dig into it deeper and investigate it. Note that this might as well has something to do with services part of Hedera, it can take some time to discover the issue while we are syncing with the other team

**Comment by Kalina-Todorova** [comment]
Hi @victorholo, @sehyoung-james after digging deeper and testing, we are unable to reproduce this issue. 
There will be a new testnet release this Thursday - can you try again then and if you are still facing this issue - please send us a code snippet so that we can properly investigate based on your use-case.

**Comment by ochikov** [comment]
Hi @victorholo, @sehyoung-james, did you get the chance to test the new version of the SDK together with the new testnet release?
