### ISSUE TITLE
Conversion from AccountID from EVM Address (AccountId.fromEvmAddress) not working

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1522]
### Description

@SimiHunjan 
Conversion from AccountID from EVM Address (AccountId.fromEvmAddress) not working.
I have an application that pairs with MetaMask. After pairing the account with EVM address: `0x0486a2be6440d655c30596926a1c22468c7873a0` is contained in the `variable selectedAccount`.

For the line
`let accountId = AccountId.fromEvmAddress(selectedAccount); //Where selectedAccount is a string containing an EVM address`

the following error is thrown:
```
EntityIdHelper.js:90 Uncaught (in promise) Error: invalid entity ID
    at Module.constructor (EntityIdHelper.js:90:1)
    at new AccountId (AccountId.js:45:1)
```
Note that other methods in `AccountId` don't error out (but also are not adequate to get the accountId string from an EVM address). For instance:

`let accountId = AccountId.fromEvmPublicAddress(selectedAccount);`
returns: `-accountId: 0.0.0x0486a2be6440d655c30596926a1c22468c7873a0`

`let accountId = AccountId.fromSolidityAddress(selectedAccount);`
returns: `-accountId: 75932350.7224009466134763154.7646023953768018848`
^ This same type of output is returned by Hethers JS utility, which is not correct or helpful. 

`let accountId = AccountId.fromString(selectedAccount);`
returns: `-accountId: 0.0.0486a2be6440d655c30596926a1c22468c7873a0`

Being unable to perform this conversion from account EVM address to account ID with the SDK or Hethers means that users are stuck. The conversion can be helpful to obtain information about the entities from HashScan, especially in the case of contracts because HashScan doesn't support searching by `contract/contractAddress`

### Steps to reproduce

1. Open [this gitpod:](https://gitpod.io/#https://github.com/ed-marquez/hedera-example-json-rpc-metamask-contracts/tree/token-associator)
2. Add the lines to the file src/components/hedera/walletConnect.js:

```
// at the top of the file
import { AccountId } from "@hashgraph/sdk";

// before the return statement of the walletConnectFcn()
let accountId = AccountId.fromEvmAddress(selectedAccount);
console.log(`-accountId: ${accountId}`);
```
3. Open the inspector
4. see outputs

### Hedera network

testnet

### Version

v2.22

### Operating system

Windows

**Comment by petreze** [comment]
@ed-marquez 
Hello, a short explanation to all of `EvmAddress` related methods in `AccountId`:

- First and foremost, all of the methods that you mentioned are creating an `AccountId` object which has the evm address as a property. Meaning that in all cases you'd have to use `accountId.evmAddress` in order to access it.

Also, the method that was added lately and supports HIP-583 is `AccountId.fromEvmPublicAddress()` which accepts 1 parameter of type `EvmAddress`. So you'd just have to access it through the `evmAddress` property of the object

Method `AccountId.fromSolidityAddress()` returns the shard, realm, and num from a solidity address. Solidity addresses are 20 bytes long and hex encoded, where the first 4 bytes represent the shard, the next 8 bytes represent the realm, and the last 8 bytes represent the num. All in Big Endian format. It basically creates an AccountId object, generated based on these requirements from above

Method `AccountId.fromString()` can accept an evm address as string (w/wo 0x prefix). The difference here from the `fromEvmPublicAddress()` method is that when we pass it as a string, we then call `EvmAddress.fromString()` which hex decodes the trimmed address without the `0x` prefix. So this is way you are getting a bit different values when comparing these two methods:
`0.0.0x0486a2be6440d655c30596926a1c22468c7873a0` vs `0.0.0486a2be6440d655c30596926a1c22468c7873a0`

**Comment by ochikov** [comment]
In addition to the comment of @petreze, I can add that you can use `fromEvmAddress`, but you need to pass `shard` and `realm` as follows: 
```
AccountId.fromEvmAddress(
        0,
        0,
        "0x0486a2be6440d655c30596926a1c22468c7873a0"
    );

**Comment by ed-marquez** [comment]
Hi @petreze and @ochikov - thank you for the detailed responses. Yes, this all makes perfect sense. I have some familiarity with the Accounts topic, and your responses were helpful. 

Let me add some clarity about what my goal is with the example I provided. 
- I'm simply trying to use the `AccountId.fromEvmAddress()` in the SDK as a utility/tool within a React app to **display** the EVM address of the account paired to my application (0x0486a2be6440d655c30596926a1c22468c7873a0) as an account id number 0.0.12345
- The reason why I'm trying to do this with the SDK is because the existing utility for this purpose in the Hethers JS library is not working as expected when doing this conversion (possibly this issue should be on their repo, but I'm unsure if we're actively maintaining that library)
- From examples I've tried using the SDK + contracts&precompiles, I remember being able to display an account ID number (0.0.12345) from a Solidity address using AccountId.fromSolidityAdress(00000000000000000000000001c3c178)
- I thought using the SDK methods would help me do this conversion from EVM address (0x0486a2be6440d655c30596926a1c22468c7873a0) to account id number (0.0.12345) from the account connected to my application

On a similar vein and about descriptions and documentation, this [doc page ](https://docs.hedera.com/hedera/core-concepts/accounts/account-properties#account-number:~:text=0.0.302d300706052b8104000a03220002d588ec1000770949ab77516c77ee729774de1c8fe058cab6d64f1b12ffc8ff07-,EVM%20Address%20Account%20Alias,-An%20EVM%20address) was recently updated with the latest terminology (public key account alias, EVM address account alias, account number alias, account number).

We should consider updating the terminology in the SDK to be consistent with that in documentation and other parts of the ecosystem (mirror node APIs, mirror node explorer, protobufs, documentation, etc.) - That's something I've discussed with @SimiHunjan before and just wanted to put it on the team's radar as well.

**Comment by petreze** [comment]
@ed-marquez 

I see what your aim is but unfortunately, it is not possible to get `0.0.12345` from the `0x0486a2be6440d655c30596926a1c22468c7873a0` evm address. Whenever you generate `AccountId` from either `fromEvmPublicAddress()` or `fromString()`, as I said, you are creating an `AccountId` object with the specified evm address as a property. All other values (i.e. shard, realm, num) are set to the default ones (in this case `0`). This is because you cannot get the `num` of `AccountId` based on the provided evm address.

The reason why you were able to gain `0.0.12345` using `AccountId.fromSolidityAdress(00000000000000000000000001c3c178)` is exactly because of the mentioned [rules](https://github.com/hashgraph/hedera-sdk-js/issues/1522#:~:text=Solidity%20addresses%20are%2020%20bytes%20long%20and%20hex%20encoded%2C%20where%20the%20first%204%20bytes%20represent%20the%20shard%2C%20the%20next%208%20bytes%20represent%20the%20realm%2C%20and%20the%20last%208%20bytes%20represent%20the%20num.%20All%20in%20Big%20Endian%20format.) and the SDK, knowing how to parse/unparse those bytes, displays them as an actual `AccountId`

**Comment by ochikov** [comment]
@ed-marquez Do you need more assistance with this issue?

**Comment by ed-marquez** [comment]
Hi @ochikov - Thank you for checking! 
All good here. I'm able to get most of the info I need directly from the EVM tools, and mirror nodes provide a way to find the equivalent account ID from an EVM address. 
 
I'll close the issue with this comment.
