### ISSUE TITLE
Automated test failure with Github Actions

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1578]
### Description

I am attempting to set up automated tests in github actions, and keep running into an issue when trying to use the Hedera sdk.

First error: Failed to fetch

Using the following code the tests were throwing a "Failed to fetch" error on execute
![image](https://user-images.githubusercontent.com/3913019/235319297-3d615556-4a16-44e5-89c3-e3b198ab4a3d.png)

![image](https://user-images.githubusercontent.com/3913019/235319373-6744554d-d5fc-4347-a40f-7703dd819494.png)

I did a bit of digging around in your guys tests, and noticed `client.setTransportSecurity(true)` so I tried adding that to the client in the above code, which did change the error into this:

![image](https://user-images.githubusercontent.com/3913019/235319362-761b2a85-5f90-461c-9127-897dd57dca57.png)

Not sure where to go from here exactly

### Steps to reproduce

It's pretty complicated to reproduce so just wanted to see if you guys had any initial thoughts

### Hedera network

testnet

### Version

24.1

### Operating system

None

**Comment by petreze** [comment]
Hello @teacoat 
First of all, the `setTransportSecurity()` method defines whether or not to connect with TLS to previewnet or testnet environments.
Also, another thing worth mentioning is that since version `2.24.1` we did pretty decent refactoring specifically on this `Mnemonic.toECDSA/ED25519PrivateKey()` functionalities. And as far as I can see in your code sample you are using the deprecated ones. We introduced new methods: `toStandardEd25519PrivateKey()` and `toStandardECDSAsecp256k1PrivateKey()`, so the equivalent to your example would be calling `await mnemonic2.toStandardEd25519PrivateKey("", 0)`

However, I have tried with both methods - the deprecated and the new ones and did not encounter the problem. Also with and without `setTransportSecurity(true)` I was able to get a successful execution of `AccountCreateTx`

Could you please try again with the latest version and latest `Mnemonic` version..

**Comment by teacoat** [comment]
Apologies I am actually using 2.24.0 - I guess the error must be with another part of this action. I will do some more troubleshooting thanks for taking a look!

**Comment by petreze** [comment]
Great, and no worries! Also do not hesitate to open another one if you encounter something else
