### ISSUE TITLE
Doesn't exist a method to revoke allowances in Fungible Tokens

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1602]
### Description

Good night,

Right now as far as I know, there isn't any method in the SDK to **revoke** an **Allowance for Fungible Tokens**. What everybody is doing is keep the same **Spender** and change the amount to **0**. This is really bad, because when we query the MirrorNode, basically It returns a lot fields with allowances, setted to 0, when It shouldn't be happening.

I'd suggest as we have a method for NFTs where we can revoke, Ex: 
```js
new AccountAllowanceDeleteTransaction().deleteAllTokenNftAllowances
```
Add the same for Fungible Tokens and Hbar. 

Also this method for NFTs, the name should be changed, because as far as I know is valid only for one NFT at once right? If we want to remove every NFT under one Token Id, we need to use: 

```js
new AccountAllowanceApproveTransaction().deleteTokenNftAllowanceAllSerials
```

So I guess it's really confused. I'd like to suggest to delete one NFT should be called: 

```js
deleteTokenNftAllowance
``` 

Or If not, modify to allow an Array of SerialNumbers under de same TokenId.

### Steps to reproduce

```js
const allowanceTrx = new AccountAllowanceApproveTransaction();
    .setMaxTransactionFee(new Hbar(maxFee))
    .approveHbarAllowance(client.operatorAccountId, spenderAccount, 0)
const txSubmit = await allowanceTrx.execute(client);


const allowanceTrx = new AccountAllowanceApproveTransaction();
    .setMaxTransactionFee(new Hbar(maxFee))
    .approveTokenAllowance(tokenId, client.operatorAccountId, spenderAccount, 0);
const txSubmit = await allowanceTrx.execute(client);

### Additional context

_No response_

### Hedera network

mainnet

### Version

2.24.1

### Operating system

Windows

**Comment by petreze** [comment]
Hey @AdriMsM91 
On the topic of adding a possibility to actually remove the allowance of a `Non-Fungible Token` being Hbar or other - it is not possible because the network does **not** support this approach. Furthermore, this is how it is working in Ethereum.

On the second topic about changing the signature of the function - first of all it is a breaking change, meaning that all usage of this functionality up until now would brake the flow in a lot of apps. Also, the first expected parameter of the current `deleteAllTokenNftAllowances()` method is of type `NftId` which is a combination of `tokenId, serialNumber`, hence paying attention to method's signature would be enough IMO

**Comment by AdriMsM91** [comment]
Fair enough @petreze then we will keep going with this. Thanks the answer!
