### ISSUE TITLE
PrivateKeys generated in sdk v1 inconsistent with v2

### ISSUE THREAD

**Issue by dractw** [hashgraph/hedera-sdk-js#1708]
### Description

Inconsistency between keys generated in sdk v1 and sdk v2

I've have a tons of keys generated in sdk v1, which actively used and now faced issue, that those keys can't be re-generated from mnemonic phrases in stable v2 sdk.

Restoring keys from bytes seems OK

### Steps to reproduce

```
const phrase = 'point mercy library solar lyrics canal reveal brick twist bounce frown purchase'

const mnem = await Mnemonic.fromString(phrase)
const hd = await mnem.toStandardEd25519PrivateKey() // v2 sdk
const pub = (await hd.derive(0)).publickKey.toString()

const legacyHd = await Ed25519PrivateKey.fromMnemonic(phrase) // v1 sdk 
const legacyPk = (await legacyHd.derive2(0)).publicKey.toString()
const legacyPub = legacyPriv.publicKey.toString()
```

Pubs generated:
v2 `302a300506032b65700321002c5499c1b70e686779e2a435a03b74c4a6e87227513c6d2ef2ea26eb76d35477`
v1 `302a300506032b657003210012df96ea987f30912494c182c2901c56a27ab45a3fcaee8de3e4ac22b7ab3c6b`

Furthermore, hd keys without derivation are different:
```
const phrase = 'point mercy library solar lyrics canal reveal brick twist bounce frown purchase'

const mnem = await Mnemonic.fromString(phrase)
const hd = await mnem.toStandardEd25519PrivateKey() // v2 sdk

const legacyHd = await Ed25519PrivateKey.fromMnemonic(phrase) // v1 sdk 

console.log(hd.toString())
console.log(legacyHd.toString())
```
v2 hd `302e020100300506032b65700422042063b2838572894f0c360752d29777f4b6c839e80aaad51705fe49cb33ed4a6972`
v1 hd `302e020100300506032b6570042204204775382768f8bb93191ffdf9a9f61ecbf7d675985171ba34ff8d575eafbc73de`

### Hedera network

mainnet

### Version

v.2.x.x

### Operating system

None

**Comment by petreze** [comment]
We did a massive refactoring around the generation of Private keys from `Mnemonic`. The previous implementation was yielding wrong keys due to wrong derivation paths - so we had to change. Use the newest implementation. Notice that there are lots of deprecations, so do not use `PrivateKey.fromMnemonic()` for example.

If you want to retrieve the previously generated keys you can try:
using your `mnem` mnemonic from your example - `await mnem.toEd25519PrivateKey()` or second option as you pointed out, restore them from bytes.
Another note: `Mnemonic.toEd25519PrivateKey()` is deprecated after the refactoring process, so use it only to derive old keys.
For any further usage, use only the non-deprecated methods after the refactoring!

Here is context in regards to the refactoring: #1550 #1350 #1356 and the mother of all - [#73](https://github.com/hashgraph/hedera-sdk-reference/issues/73)

**Comment by dractw** [comment]
@petreze Ty for quick response, will try your suggestion and get back with an update

**Comment by dractw** [comment]
@petreze Unfortunaly, no luck. 
Deprecated `Mnemonic.toEd25519PrivateKey()` still generates hd-key different to sdk1 `PrivateKey.fromMnemonic()` does.

Is there any other workarounds to restore those keys from mnemonic.
Generating it from bytes requires to use sdk v1 `Ed25519PrivateKey.fromMnemonic(phrase).toBytes()` which i try to fully remove with sdk v2

**Comment by dractw** [comment]
@petreze actually it does in v1 sdk

**Comment by ochikov** [comment]
Hello @dractw,  Do you need further assistance with this issue?

**Comment by petreze** [comment]
Hey @dractw 
A quick note after some tests: v2 keys generated equal v1 generated keys after `.derive(0)`
i.e:

```
const phrase = 'point mercy library solar lyrics canal reveal brick twist bounce frown purchase'
const mnem = await Mnemonic.fromString(phrase);

const hd = await mnem.toEd25519PrivateKey("");
const v1Derived = await hd.derive(0);
console.log(`v1 derived: ${v1Derived} <-- like v2 hd`);

const hd2 = await mnem.toStandardEd25519PrivateKey();
console.log(`v2: ${hd2.toString()}`);
```

These from above are equal because in v1 the keys generated were one level above from the one needed

**Comment by petreze** [comment]
@dractw 
In regards to your comment `Generating it from bytes requires to use sdk v1 Ed25519PrivateKey.fromMnemonic(phrase).toBytes() which i try to fully remove regarding to sdk v2 usage.`

A workaround using version 2 of the SDK I was able to recover `302e020100300506032b6570042204204775382768f8bb93191ffdf9a9f61ecbf7d675985171ba34ff8d575eafbc73de` key as follows:
- cast the private key generated using v1 `.toBytes()`
- get those bytes and pass them here `PrivateKey.fromBytes(bytesFromV1)` <- this is using v2 functionality of the SDK

The thing is that the version you have been using (1.4.7) is about 2 years old and then, the SDK has been in his nascent time and a lot of things has changed since then. Its not only the massive refactoring that I have mentioned previously

**Comment by petreze** [comment]
@dractw 
Alternatively, you could still generate it with `fromString()` and work use it within the SDK

Does these approaches fix your issue? Could we close the ticket?

**Comment by teacoat** [comment]
I am encountering a similar situation and, after many hours of smashing my head against the keyboard, was able to get the key I wanted using .toEd25519PrivateKey().

I would like to know if there are any concerns around users continuing to use these keys, and the long term plans around supporting this function.

**Comment by dractw** [comment]
@teacoat Hi there, could you share your workaround to generate those keys? My workaround was just to hardcode the v1 generation function as an utility and get rid of sdk-v1 completely :)
