### ISSUE TITLE
ContractCallQuery requires massive tx fee on testnet

### ISSUE THREAD

**Issue by Perseverance** [hashgraph/hedera-sdk-js#179]
I am going through the examples - the one for deploying stateful smart contract. When it comes to the contract call:
```
let callResult = await new ContractCallQuery()
			.setContractId(newContractId)
			.setGas(1000) // ~897
			.setFunction("getMessage", null)
			.execute(client);
```
it fails with:
```
MaxQueryPaymentExceededError: query cost of 1038336.2 HBAR exceeds max set on client: 1 HBAR
```

I might be confused but 1038336.2 HBAR seems like quite a lot for contract call. Am I missing something?

**Comment by Cooper-Kunz** [comment]
Hey @Perseverance - I could also be mistaken, but my initial guess is that you're paying 1038336.2 tinybars, instead of hbars. Hedera defaults tx fees to this denomination, similarly to sats in Bitcoin. 

You can check out the fees and hbar denominations [within the docs](https://docs.hedera.com/guides/mainnet/fees). 

According to this, a contractCallQuery should cost ~1.2hbar, since fees are pegged to USD and have a lower bound of $0.04 cents on mainnet right now. 

![Screen Shot 2020-01-29 at 11 54 14 AM](https://user-images.githubusercontent.com/11776938/73387670-1e568f80-428e-11ea-80b0-a0e54649c7c2.png).

Also, you can look up the tx on an explorer like [DragonGlass](https://testnet.dragonglass.me/hedera/home) to see what was charged vs attempted. 

@mehcode or perhaps even @paulmadsenhed could clarify if I'm off here.

**Comment by Perseverance** [comment]
Hey Cooper, Thanks for your response. It specifically says HBARS in the error, and also it triggers the requirement for less than 1 HBAR cost of my client instance, so it is actually requesting to use Hbars not Tinybars.

**Comment by Cooper-Kunz** [comment]
No problems at all @Perseverance - I may be misunderstanding the issue...  

But have you tried [explicitly importing](https://github.com/hashgraph/hedera-sdk-js/blob/1b8350fd514c36b30a8ff0855a8c7815248f8937/examples/create-stateful-contract.js#L2) `Hbar` from the SDK, and using it like [this example](https://github.com/hashgraph/hedera-sdk-js/blob/1b8350fd514c36b30a8ff0855a8c7815248f8937/examples/create-stateful-contract.js#L36)?

**Comment by Perseverance** [comment]
Yes, I did copy paste the example as it is there :(. Intentionally stripped my script to only the bare minimum. As for gas - I think setGas only works with number and not Hbar. Might it be that Gas is interpreted internally as Hbar instead of Tinybar, thus Gas*operations would end up with the huge fee?

**Comment by Cooper-Kunz** [comment]
Following up here @Perseverance - I just chatted with @paulmadsenhed to make sure I wasn't crazy.

A query will run (and charge) the max fee that is set. So I've been trying to run a ContractCallQuery() myself, and have had similar experiences. I'm currently getting charged 43ℏ for [the query](https://testnet.dragonglass.me/hedera/transactions/001422931580330228502000000), even after attempting to overwrite the max tx fee.. which seems problematic 😄 

```
 const callResult = await new ContractCallQuery()
      .setContractId(receipt._contractId.toString())
      .setGas(1000)
      .setMaxQueryPayment(Hbar.of(2))
      .setFunction("getMessage", null)
      .execute(hederaClient);
```

Maybe time to see if @mehcode can help out?

**Comment by mehcode** [comment]
Hey guys. I will escalate now to our SDK team and see what's going on. Thanks for opening the issue.

**Comment by paulmadsenhed** [comment]
the fee for a ContractCallQuery *should *be ~ 0.025 hbars (as the base price is fixed at 0.001 USD  and the exchange rate is currently locked at 0.04 usd).

The cryptotransfer that pays the node for the query should have a value in this range (expressed in tinybars though)

**Comment by mehcode** [comment]
To be clear this was just a bug in our SDK on Contract Call. We've fixed this on master and are preparing a patch release.

**Comment by mehcode** [comment]
Release as v1.1.4
