### ISSUE TITLE
Operator Signer Transaction Bytes

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1801]
### Problem

When using the operator signer flow, the signer does not have access to the transactionBytes, only the bodyBytes. This could be improved so the user knows what they are signing.

Here is some example code:

```
let client = Client.forNetwork(network_env as any);

const genericSigner = message => sign(message);
const pubKey = "<public_key>";
const accId = "<account_id>";

client.setOperatorWith(accId, pubKey, genericSigner);
```

In this example, whatever is handling the sign() in genericSigner is unable to display details of what the user is signing as message is bodyBytes.

### Solution

The code that calls this signer is signWith() in Transaction.js (https://github.com/hashgraph/hedera-sdk-js/blob/bc6611779343fe5bc43cccb6c5df61969b7cfd03/src/transaction/Transaction.js#L636C5-L636C5), specifically this line https://github.com/hashgraph/hedera-sdk-js/blob/bc6611779343fe5bc43cccb6c5df61969b7cfd03/src/transaction/Transaction.js#L683C38-L683C38

Adding a parameter to pass in the full transaction bytes to the signer could resolve this, unless there is an existing way to reconstruct the transaction from bodyBytes.

**Comment by SimiHunjan** [comment]
hey @teacoat! I wanted to circle back on the flow you described yesterday. Is the following correct?

- The dapp constructs the transaction with the properties required for the transaction (I believe this would be equivalent to the `message` in your code)
- The dapp sends the `message` to the wallet for the user to sign
- When the message is passed to the wallet the wallet needs to be able to view the `message` content and display it to the user in the wallet before they sign
- With the above flow (using `sign()` and then passing it into the `client.setOperatorWith(`)) we are not able to return/access the contents in the` message`

**Comment by SimiHunjan** [comment]
What transaction type is being signed in `message`?

**Comment by SimiHunjan** [comment]
Noting some comments on this issue that were discussed:

@SimiHunjan :
Not sure if this flow would work:
Dapp creates the transaction
Dapp freezes the transaction
Dapp sends it to the wallet
Wallet displays the transaction details as I believe you would get the details from the transaction bytes
Wallet signs the transaction and executes


@gregscullard   
Your suggested flow would work, but I guess they want to use a signer which exposes the appropriate interface and let the SDK deal with the interaction with the signer which could be "anything".

The challenge with transferring full transaction bytes is that if the signer is "dumb" like a HSM, it will not know how to unpack the transaction bytes and sign individual transactions within, we can't assume a signer will have an SDK, it may just be an ED25519 library that knows how to sign a transaction.

I think this needs more thought in the sense that if we start shipping transaction bytes rather than body bytes in that operation, we'll break existing signer implementations.

**Comment by teacoat** [comment]
@SimiHunjan It could be any type of transaction.

The flow is more like:
- dapp constructions transaction
- dapp tries to execute the transaction with .execute() using a client with a function as an operator
- operator function calls whatever is being used to sign and passes `message` (which is the bodyBytes)

In general, I would say getting the transaction details to the signer is a basic functionality that is needed for most cases and not having it is an oversight - because people need to know what they are signing (trust, but verify).

Like I said, I am not super familiar with exactly what is going on here regarding the internals of the sdk, I just know the end result I am looking for, which is a flexible way to use .execute() or something similar where we can basically hot-swap the signer.

**Comment by SimiHunjan** [comment]
@teacoat is this issue still priority for you?

**Comment by SimiHunjan** [comment]
Please reopen if this is needed. Closing for now.
