### ISSUE TITLE
When creating a new account via transfer, the EVM address is not always retrievable from the tx record 

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#2268]
### Description

When auto-creating accounts:
- If you transfer to an **account alias,** the **EVM address is** retrievable from the transaction record
- If you transfer to an **EVM address**, the **EVM address is not** retrievable from the transaction record

**The EVM address should be retrievable from the record in both cases.** 
The users could theoretically match EVM addresses that they send HBAR to and account IDs from their code, but there are various scenarios that could complicate that dynamic to ensure an actual match.

  

### Steps to reproduce

See this code:
https://github.com/ed-marquez/hedera-auto-account-creation-transfer-to-evm/blob/769b0c0d6ecd00041c9926f45208e27a718eb4d4/index.js#L22C1-L23C46 

Try the code while performing HBAR transfers to:
1. `newEvmAddressArray`
2. `newAccountAliasArray`

Notice that when sending to `newEvmAddressArray`, the EVM address of the newly created account is not retrievable from the record.

### Hedera network

mainnet, testnet

### Version

2.44.0

### Operating system

Windows

**Comment by SimiHunjan** [comment]
I think this issue is for Services and not the SDKs. We return what is defined in the transaction record for a transaction as defined in the protobufs.

You can see the definition here:

https://github.com/hashgraph/hedera-protobufs/blob/main/services/transaction_record.proto#L151

It mentions the following about EVM addresses when included in the transaction body:

     * The new default EVM address of the account created by this transaction.
     * This field is populated only when the EVM address is not specified in the related transaction body.
     */
    bytes evm_address = 21;
 

> This field is populated only when the EVM address is not specified in the related transaction body.


When you transfer to an EVM address is part of the data that is submitted within the transfer transaction body so it seems that it is intentionally not returned in the record when it is this case.

**Comment by SimiHunjan** [comment]
@tinker-michaelj can you please confirm this behavior?

**Comment by Neeharika-Sompalli** [comment]
@ed-marquez 
I agree with @SimiHunjan . That field is set only when we create a new account using `CryptoCreate` using key alias. In that scenario we will export the extracted EVM address associated to that newly created account Id.

**Comment by SimiHunjan** [comment]
Thanks @Neeharika-Sompalli. @ed-marquez if you expect any change to this behavior in the node software you can follow-up with Doug/Nana.
