### ISSUE TITLE
Mnemonics -> ECDSA key -> ECDSA key doesn't yield same public key

### ISSUE THREAD

**Issue by Volind** [hashgraph/hedera-sdk-js#2419]
### Description

I'm recovering a private key from Mnemonics and printing the public key as a string.
I then use the private key string above to instantiate a PrivateKey and print its public key as a string.
The two public keys differ, yet printing both private keys as string yield the same result, see example below

### Steps to reproduce

```
import {Mnemonic, PrivateKey} from "@hashgraph/sdk";

const seedStr = "marriage bounce fiscal express wink wire trick allow faith mandate base bone";
const mnemonic = await Mnemonic.fromString(seedStr);
const privateKey = await mnemonic.toStandardECDSAsecp256k1PrivateKey();
const publicKeyStr = privateKey.publicKey.toStringRaw();
console.log("Public from PrivateKey directly: ", publicKeyStr);

const privateKeyStr = privateKey.toStringDer();
console.log("PrivateKey directly: ", privateKeyStr);

const privateKeyFromStr = await PrivateKey.fromStringDer(privateKeyStr);
const privateKeyFromStrStr = privateKeyFromStr.toStringDer();
console.log("PrivateKey after conversion from string: ", privateKeyFromStrStr);


const brokenPublicKeyStr = privateKeyFromStr.publicKey.toStringRaw();
console.log("Public from PrivateKey string: ", brokenPublicKeyStr);

console.log("Private keys string matching: ", privateKeyStr === privateKeyFromStrStr);
console.log("Public Keys matching: ", publicKeyStr === brokenPublicKeyStr);
```

outputs:

```
Public from PrivateKey directly:  036ebe6dffaa5290f002a790a7f1db0e0984332ed0c3b2906f2134db05294871ab
PrivateKey directly:  3030020100300706052b8104000a04220420a5b9dedc7c7767c4a88a0ac3cc6b9171948bada579226bd550d3342db11dc800
PrivateKey after conversion from string:  3030020100300706052b8104000a04220420a5b9dedc7c7767c4a88a0ac3cc6b9171948bada579226bd550d3342db11dc800
Public from PrivateKey string:  03009472c2a77901577f8a60b10e13cd77748a49fb4aa03e711e615c55aaf8f3d2
Private keys string matching:  true
Public Keys matching:  false
```

Issue is the same as [https://github.com/hashgraph/hedera-sdk-js/issues/1396](https://github.com/hashgraph/hedera-sdk-js/issues/1396) but I have no permissions to reopen it.

### Hedera network

mainnet, testnet, previewnet

### Version

v2.48.1

### Operating system

None

**Comment by Neurone** [comment]
Hi, I have been digging into the code and think I have found the problem.

The source of the mismatch is how we manage the private keys: we use `Uint8Array`, but the low-level libraries usually use `BigNumber` internally. I have tested both the native NodeJS elliptic library and several others (e.g. [elliptic](https://www.npmjs.com/package/elliptic)), and the behaviour is always the same.

Specifically, the problem is with the [`fromBytes' function](https://github.com/hashgraph/hedera-sdk-js/blob/238f0c7905b84cfbd8f8bb55ed97750d8e796644/packages/cryptography/src/primitive/ecdsa.js#L37):

```JavaScript
export function fromBytes(data) { const keypair = secp256
    const keypair = secp256k1.keyFromPrivate(data)

    return { privateKey
        privateKey: hex.decode(keypair.getPrivate("hex"))
        publicKey: hex.decode(keypair.getPublic(true,"hex"))
    };
}
```

When we ask the `secp256k1` library to manage the private key (or a derived private key), it stores the data internally as a `BN`. When we query the private key with the `getPrivate("hex")` function as a number, it strips off all leading zeros. This means that when we build the `Uint8Array` we end up with fewer elements than expected.

When I do some tests, I usually randomly get 31 bytes of private keys, but less is possible. And we know that keys smaller than 32 bytes make our SDK very unhappy.

To avoid errors, the SDK constructs 32-byte fixed arrays, adding the missing bytes as trailing zeros when using the `toStringDer()` function, because it uses the [toBytesDer() function](https://github.com/hashgraph/hedera-sdk-js/blob/238f0c7905b84cfbd8f8bb55ed97750d8e796644/packages/cryptography/src/EcdsaPrivateKey.js#L169) under the hood, and this is why the two keys pass the equality check.

In fact, when we create the new key from the first one, the new key uses the trailing zeros, and so even though they are different under the hood, the private keys appear to be the same as strings. To see the difference try to use:

```JavaScript
console.log(JSON.stringify(privateKeyStr))
console.log(JSON.stringify(privateKeyFromStrStr))
```

**A quick fix would be to restore the leading zeros in the `privateKey` variable before returning the `KeyPair` object, but I suggest extensive testing to see if this problem is present elsewhere in the code.** 

And I suggest adding some unit tests for these cases as well.

This is a simple script to test the `secp256k1` library, showing how it (correctly) ignores leading zeros when setting private keys:

```JavaScript
import elliptic from "elliptic";
const secp256k1 = new elliptic.ec("secp256k1");

let data = Buffer.from("0083118d0b0545cc6ef4b00b09c79fd96aa816a494fe0f8dc21d4129aa0775b6", "hex");
console.log("data", data);                      // Data cointains leading zero bytes
let keypair = secp256k1.keyFromPrivate(data);
console.log(keypair.getPrivate())
console.log(keypair.getPrivate("hex"))          // 83118d0b0545cc6ef4b00b09c79fd96aa816a494fe0f8dc21d4129aa0775b6
console.log(keypair.getPublic(true, "hex"))     // 031b7932bf5572a165c885d6153859ce4ae2fc2b791bb5e28bf44e44430901ddd5

// Results does not change using a "different" private key, because the library consider BN not byte arrays
data = Buffer.from("83118d0b0545cc6ef4b00b09c79fd96aa816a494fe0f8dc21d4129aa0775b6", "hex");
console.log("data", data);                      // Data does NOT contain leading zero bytes
keypair = secp256k1.keyFromPrivate(data);
console.log(keypair.getPrivate())
console.log(keypair.getPrivate("hex"))          // 83118d0b0545cc6ef4b00b09c79fd96aa816a494fe0f8dc21d4129aa0775b6
console.log(keypair.getPublic(true, "hex"))     // 031b7932bf5572a165c885d6153859ce4ae2fc2b791bb5e28bf44e44430901ddd5
```
