### ISSUE TITLE
(v2.0.1) - Should signing transaction bytes work ?

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#299]
Trying this
```
const sigKey = await PrivateKey.fromString(getPrivateKeyForAccount(destination));
const signature = await sigKey.sign(tx.toBytes());
tx.addSignature(sigKey.publicKey, signature);
const result = await tx.execute(client);
```

results in `receipt for transaction xxxxx contained error status INVALID_SIGNATURE`

**Comment by danielakhterov** [comment]
No, you must deserialize the transaction using `Transaction.fromBytes()` first. The reason for this is because the byte representation of `Transaction.toBytes()` is actually all the protobuf `Transaction` messages length-delimited encoded one after other. To sign the transaction you would need to decode the transaction, sign the `ProtoTransaction.bodyBytes` and append that signature to the `ProtoTransaction.sigMap`.

**Comment by gregscullard** [comment]
Ok, understood. Closing.
