### ISSUE TITLE
.setMaxTransactionFee appears to be ignored

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#320]
Hi, trying to create a token with the following from the examples

```
    resp = await new TokenCreateTransaction()
        .setMaxTransactionFee(new Hbar(100))
        .setNodeAccountIds([resp.nodeId])
        .setTokenName("ffff")
        .setTokenSymbol("F")
        .setDecimals(3)
        .setInitialSupply(100)
        .setTreasuryAccountId(client.operatorAccountId)
        .setAdminKey(client.operatorPublicKey)
        .setFreezeKey(client.operatorPublicKey)
        .setWipeKey(client.operatorPublicKey)
        .setKycKey(client.operatorPublicKey)
        .setSupplyKey(client.operatorPublicKey)
        .setFreezeDefault(false)
        .execute(client);
```

and getting an `INSUFFICIENT_TX_FEE` error. Changing the value for `setMaxTransactionFee` to 1000 results in the same error. Tried the `HBar.from` variant and the result is the same.

**Comment by gregscullard** [comment]
A lower fee using the go sdk (40) works fine.

**Comment by danielakhterov** [comment]
I believe this was fixed awhile ago, but was not released due to some internal confusion. I just release v2.0.12. I tested this using `TokenCreateIntegrationTest` by setting `setMaxTransactionFee(new Hbar(10))` which caused the test to fail as expected. I think shows that it does override the default max fee. In contrast if I didn't set the max fee the tests passes.

**Comment by gregscullard** [comment]
Works with latest SDK indeed. Thanks for your help.
