### ISSUE TITLE
Cannot sign transactions with ECDSA key

### ISSUE THREAD

**Issue by joan41868** [hashgraph/hedera-sdk-js#844]
### Description

When submitting a transaction, signed with an ECDSA key, we get an `INVALID_SIGNATURE` precheck. 

### Steps to reproduce

Run this code:
```javascript

const edPrivateKey = PrivateKey.fromString(account.operator.privateKey);
const client = Client.forNetwork(account.network)
   .setOperator(account.operator.accountId, edPrivateKey);
const key = PrivateKey.generateECDSA();
const accountCreate = await new AccountCreateTransaction()
   .setKey(key.publicKey)
   .setInitialBalance(new Hbar(5))
   .execute(client);
const receipt = await accountCreate.getReceipt(client);
console.log(receipt);

const newAccountId = receipt.accountId.toString();

const transferTx = await new TransferTransaction()
   .addHbarTransfer(newAccountId, new Hbar(-0.1))
   .addHbarTransfer("0.0.1340", new Hbar(0.1))
   .setNodeAccountIds([new AccountId(0,0,3)])
   .setTransactionId(TransactionId.generate(newAccountId))
   .freeze()
const signed = await transferTx.sign(key);
const transferResponse = await signed.execute(client);
console.log(transferResponse); // -> INVALID_SIGNATURE

```

### Hedera network

previewnet

### Version

latest

### Operating system

Linux

**Comment by danielakhterov** [comment]
I did some poking and this definitely is a bug, but I was not really able to find out what the bug is. The same code in Java works, but in JS it doesn't even though we have a unit tests that confirms both SDKs produce exactly the same signature for the same message. Perhaps it has something to do with `sign` although that'd be weird considering it's a simple wrapper for `signWith`.

**Comment by danielakhterov** [comment]
Should of linked the issue in the PR; I believe this is fixed now and hence closing.
