### ISSUE TITLE
Add type DelegateContractId 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#851]
### Problem

SDK currently do not support this type that is needed for contracts.

### Solution

Add support

**Comment by gregscullard** [comment]
Note that in the HAPI specification, a ContractId is a valid Key, can we extend the Key type within the SDKs to allow a ContractId to be specified rather than creating a new type/builder ?

Note sure of the ramifications of this proposal, but it would be more closely aligned to the notion of a contract acting as a key.
