### ISSUE TITLE
Receipt toBytes() and then fromBytes() missing token id

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#956]
### Description

When converting a transaction receipt to bytes and back token id is missing.

I am using v2.7.1 but have tried in 2.9.1 and the issue remains.

### Steps to reproduce

1) Do a token create transaction
2) Get receipt
3) Convert to bytes and back
```
const rec = await val.getReceipt(client);
console.log(rec);
let test2 = TransactionReceipt.fromBytes(rec.toBytes());
console.log(test2);
```

### Additional context

Before toBytes:
![image](https://user-images.githubusercontent.com/3913019/154865672-e295ba16-56f0-419f-ba70-0aa84366f966.png)

After fromBytes:
![image](https://user-images.githubusercontent.com/3913019/154865682-3e5c3919-f6c0-4855-af11-3826b27a4337.png)

### Hedera network

testnet

### Version

2.7.1

### Operating system

Linux

**Comment by danielakhterov** [comment]
I believe this is already fixed on `develop`, but our unit test was only testing `TransactionReceipt.[_to|_from]Protobuf()` instead of `TransactionReceipt.[to|from]Bytes()` I adjust that along with fixing some of the issues raised from that change here: https://github.com/hashgraph/hedera-sdk-js/commit/f73d6b62d4d743281c757d392a50d805b48e466b#diff-562c7392e5f0ca5781d13fa1e23ca2f0ea2de990497d9d1ff527599a99d26026R60
This will be part of the 2.11.0-beta.1 release.

**Comment by teacoat** [comment]
Thank you @danielakhterov !
